# Generated by Django 3.2.5 on 2021-07-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20210723_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='company',
        ),
        migrations.AddField(
            model_name='review',
            name='company',
            field=models.ManyToManyField(to='userapp.Company'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.ManyToManyField(to='userapp.Ratings'),
        ),
    ]
