# Generated by Django 3.2.5 on 2021-07-24 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_ratings_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='rating',
            new_name='ratings',
        ),
    ]
