# Generated by Django 3.2.5 on 2021-07-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_rename_rating_ratings_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='other',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
