# Generated by Django 3.2.5 on 2021-07-29 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_review_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('createdate', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.company'),
        ),
    ]
