# Generated by Django 3.2.5 on 2021-07-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_auto_20210730_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
